# Generated by Django 4.0.6 on 2022-08-03 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentedBooks',
            new_name='RentedBook',
        ),
        migrations.CreateModel(
            name='RequestedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('isbn_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('book_status', models.CharField(choices=[('ORDERD', 'orderd'), ('PENDING', 'pending'), ('DELIVERED', 'delivered')], default='ORDERD', max_length=20)),
                ('request_status', models.CharField(choices=[('REQUESTED', 'requested'), ('CANCELED', 'canceled')], default='REQUESTED', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
