# Generated by Django 4.0.6 on 2022-08-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_rentedbooks_rentedbook_requestedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedbook',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
