# Generated by Django 4.0.6 on 2022-08-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_requestedbook_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedbook',
            name='book_status',
            field=models.CharField(choices=[('SEARCHING', 'searching'), ('ORDERD', 'orderd'), ('PENDING', 'pending'), ('DELIVERED', 'delivered')], default='SEARCHING', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestedbook',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
